/**
 * The icon vocabulary.
 *
 * One place, so a glyph means the same thing everywhere and nothing is drawn
 * with an emoji. Emoji are a typeface accident: they render differently on
 * every machine, they carry a cartoon register this application should not
 * have, and half of them are unreadable at 14 px. Lucide is a stroked set at a
 * single weight, which sits correctly next to the interface's type.
 */
import {
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Boxes,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  Circle,
  CircleDashed,
  CircleDot,
  Crosshair,
  Equal,
  Eye,
  EyeOff,
  FileText,
  Flame,
  Gauge,
  Grid3x3,
  HelpCircle,
  Home,
  Layers,
  Minus,
  Pause,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  RotateCcw,
  Ruler,
  ScanLine,
  Search,
  ShieldCheck,
  SkipBack,
  SkipForward,
  SlidersHorizontal,
  Sparkles,
  Stethoscope,
  X,
  ZoomIn,
  ZoomOut,
  type LucideIcon,
} from "lucide-react";

export {
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Boxes,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  Circle,
  CircleDashed,
  CircleDot,
  Crosshair,
  Equal,
  Eye,
  EyeOff,
  FileText,
  Flame,
  Gauge,
  Grid3x3,
  HelpCircle,
  Home,
  Layers,
  Minus,
  Pause,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  RotateCcw,
  Ruler,
  ScanLine,
  Search,
  ShieldCheck,
  SkipBack,
  SkipForward,
  SlidersHorizontal,
  Sparkles,
  Stethoscope,
  X,
  ZoomIn,
  ZoomOut,
};
export type { LucideIcon };

/** The verdict vocabulary, as icons rather than as characters. */
export const VERDICT_ICONS: Record<string, LucideIcon> = {
  check: Check,
  down: ArrowDown,
  equal: Equal,
  up: ArrowUp,
  plus: Plus,
  question: HelpCircle,
  minus: Minus,
  dot: CircleDot,
  alert: AlertTriangle,
};
